### ISSUE TITLE
Import fail via Vagrant repository

### ISSUE THREAD

**Issue by berdav** [therealbobo/pwnvm#2]
Importing the virtual machine via vagrant repository result in an error.

```
Stderr: VBoxManage: error: RawFile#0 failed to create the raw output file /home/robi/Documents/projects/pwnvm/ubuntu-bionic-18.04-cloudimg-console.log (VERR_FILE_NOT_FOUND)
```

Probably it is related to a local file path.

**Comment by therealbobo** [comment]
The ubuntu/bionic64 image has the uart enabled. I disabled the uart fixing the problem.
